from typing import Any, Dict, List
from fastapi import APIRouter
from app.digital_twin import DigitalTwinConfig, DigitalTwinGenerator

router = APIRouter(prefix="/digital-twin", tags=["Digital Twin"])


@router.get("/transactions", summary="List synthetic transactions")
def get_synthetic_transactions() -> List[Dict[str, Any]]:
    """Retrieve synthetic transactions generated by the Digital Twin."""
    twin = DigitalTwinGenerator(DigitalTwinConfig.dev_preset(seed=42)).generate()
    results = []
    for tx in twin.transactions:
        tx_dict = {
            "id": str(tx.id),
            "user_id": str(tx.user_id),
            "account_id": str(tx.account_id),
            "device_id": str(tx.device_id),
            "merchant_id": str(tx.merchant_id),
            "amount": float(tx.amount),
            "currency": str(tx.currency),
            "payment_rail": str(tx.payment_rail),
            "timestamp": tx.timestamp.isoformat() if hasattr(tx.timestamp, "isoformat") else str(tx.timestamp),
            "hour": getattr(tx, "hour", 14),
            "is_weekend": getattr(tx, "is_weekend", False),
            "status": str(tx.status),
            "risk_score": 85.5 if tx.is_adversarial else 12.0,
            "decision": "BLOCK" if tx.is_adversarial else "APPROVE",
            "campaign_id": "CAMP_BEHAVIORAL_MIMICRY_01" if tx.is_adversarial else None,
            "is_adversarial": bool(tx.is_adversarial),
        }
        results.append(tx_dict)
    return results
