import { fetchJson } from './client';
import { ExplanationResult } from './types';

export async function explainTransaction(
  transactionId?: string,
  includeCounterfactuals: boolean = true
): Promise<ExplanationResult> {
  try {
    return await fetchJson<ExplanationResult>('/explainability/explain', {
      method: 'POST',
      body: JSON.stringify({
        transaction_id: transactionId,
        include_counterfactuals: includeCounterfactuals,
        seed: 42,
      }),
    });
  } catch (err) {
    console.warn('[VEXORA Sandbox API] Using fallback ExplanationResult demo data');
    const txId = transactionId || 'TX_SYN_00000001';
    return {
      explanation_id: `EXP_DEMO_${txId.slice(-8)}`,
      provenance: {
        explanation_id: `EXP_DEMO_${txId.slice(-8)}`,
        transaction_id: txId,
        campaign_id: 'CAMP_BEHAVIORAL_MIMICRY_01',
        genome_id: 'SYN_GENOME_000001',
        model_version: 'v1.1.0-cand-42',
        dataset_reference: 'SYNTHETIC_DIGITAL_TWIN_DEV',
        random_seed: 42,
        generated_at: new Date().toISOString(),
        source_subsystem: 'EXPLAINABILITY_ENGINE',
        source_artifacts: [
          'data/evaluations/evaluation_report.json',
          'models/blue_team/active_model.json',
        ],
      },
      primary_decision: 'BLOCK',
      composite_risk_score: 85.5,
      why_flagged_ranking: [
        {
          evidence_id: 'EVI_DEMO_01',
          category: 'RULE',
          source_subsystem: 'RULE_ENGINE',
          summary: 'Rule Triggered: High Amount Spike (ID: R001)',
          detail: { observed: 45000.0, threshold: 50000.0 },
          normalized_strength: 0.85,
          relevance_explanation: 'Rule R001 observed value exceeded standard baseline threshold.',
        },
        {
          evidence_id: 'EVI_DEMO_02',
          category: 'FUSION',
          source_subsystem: 'ML_DETECTOR',
          summary: 'Detector Triggered: ML_DETECTOR (Risk: 76.8/100)',
          detail: { raw_score: 0.768, normalized_score: 76.8, confidence: 0.85 },
          normalized_strength: 0.65,
          relevance_explanation: 'High risk contribution from Transaction ML detector layer.',
        },
        {
          evidence_id: 'EVI_DEMO_03',
          category: 'ADVERSARIAL',
          source_subsystem: 'RED_TEAM_ATTACK_ENGINE',
          summary: 'Adversarial Attack Campaign: BEHAVIORAL_MIMICRY',
          detail: { genome_id: 'SYN_GENOME_000001', fidelity_score: 0.92 },
          normalized_strength: 0.92,
          relevance_explanation: 'Red Team synthesized attack scenario targeting defense infrastructure.',
        },
      ],
      detector_evidences: {
        rules: {
          detector_name: 'RULES_DETECTOR',
          detector_version: '1.0.0',
          raw_score: 0.40,
          normalized_score: 40.0,
          triggered: true,
          confidence: 0.85,
          contribution_weight: 0.20,
          decision_relevance: 'SECONDARY_SIGNAL',
        },
        ml: {
          detector_name: 'ML_DETECTOR',
          detector_version: '1.0.0',
          raw_score: 0.768,
          normalized_score: 76.8,
          triggered: true,
          confidence: 0.85,
          contribution_weight: 0.30,
          decision_relevance: 'PRIMARY_SIGNAL',
        },
        behavioral: {
          detector_name: 'BEHAVIORAL_DETECTOR',
          detector_version: '1.0.0',
          raw_score: 0.65,
          normalized_score: 65.0,
          triggered: true,
          confidence: 0.80,
          contribution_weight: 0.20,
          decision_relevance: 'PRIMARY_SIGNAL',
        },
        graph: {
          detector_name: 'GRAPH_DETECTOR',
          detector_version: '1.0.0',
          raw_score: 0.25,
          normalized_score: 25.0,
          triggered: false,
          confidence: 0.75,
          contribution_weight: 0.15,
          decision_relevance: 'SECONDARY_SIGNAL',
        },
        adversarial: {
          detector_name: 'ADVERSARIAL_DETECTOR',
          detector_version: '1.0.0',
          raw_score: 0.90,
          normalized_score: 90.0,
          triggered: true,
          confidence: 0.90,
          contribution_weight: 0.15,
          decision_relevance: 'PRIMARY_SIGNAL',
        },
      },
      fusion_evidence: {
        composite_risk_score: 85.5,
        final_decision: 'BLOCK',
        layer_scores: { rules: 40.0, ml: 76.8, behavioral: 65.0, graph: 25.0, adversarial: 90.0 },
        layer_weights: { rules: 0.20, ml: 0.30, behavioral: 0.20, graph: 0.15, adversarial: 0.15 },
        reason_codes: ['ML_HIGH_RISK', 'BEHAVIORAL_ANOMALY', 'ADVERSARIAL_PATTERN_MATCH'],
      },
      rule_evidences: [
        {
          rule_id: 'R001',
          rule_name: 'High Amount Spike',
          triggered: true,
          observed_value: 45000.0,
          threshold_value: 50000.0,
          severity: 'HIGH',
          source_transaction_id: txId,
        },
        {
          rule_id: 'R003',
          rule_name: 'High Session Velocity',
          triggered: true,
          observed_value: 6,
          threshold_value: 5,
          severity: 'HIGH',
          source_transaction_id: txId,
        },
      ],
      feature_evidences: [
        {
          feature_name: 'amount',
          feature_value: 45000.0,
          contribution: null,
          direction: null,
          model_version: 'v1.1.0-cand-42',
          transaction_id: txId,
          attribution_available: false,
          unavailability_reason:
            'Per-sample SHAP tree attribution not configured for lightweight RandomForest',
        },
        {
          feature_name: 'device_trust_score',
          feature_value: 0.15,
          contribution: null,
          direction: null,
          model_version: 'v1.1.0-cand-42',
          transaction_id: txId,
          attribution_available: false,
          unavailability_reason:
            'Per-sample SHAP tree attribution not configured for lightweight RandomForest',
        },
      ],
      anomaly_evidence: {
        anomaly_score: 0.65,
        anomaly_threshold: 0.50,
        triggered: true,
        baseline_reference: 'BENIGN_BASELINE_DISTRIBUTION',
        transaction_id: txId,
      },
      graph_evidence: {
        graph_risk_score: 0.25,
        triggered: false,
        node_identifiers: {
          user_id: 'USER_SYN_000001',
          account_id: 'ACC_SYN_000001',
          device_id: 'DEV_SYN_000001',
        },
        connected_component_size: 1,
        suspicious_network_indicators: [],
        transaction_id: txId,
      },
      attack_evidence: {
        genome_id: 'SYN_GENOME_000001',
        genome_version: '1.0.0',
        attack_family: 'BEHAVIORAL_MIMICRY',
        payment_rail: 'UPI',
        mutation_parameters: { intensity: 1.0, target_population: 'HIGH_BALANCE_ACCOUNTS' },
        parent_genome_id: null,
        campaign_id: 'CAMP_BEHAVIORAL_MIMICRY_01',
        affected_transaction_id: txId,
        behavioral_fidelity_score: 0.92,
      },
      bypass_evidence: {
        genome_id: 'SYN_GENOME_000001',
        affected_transaction_id: txId,
        layer_bypass_status: {
          rules: 'DETECTED',
          ml: 'DETECTED',
          behavioral: 'DETECTED',
          graph: 'BYPASSED',
          adversarial: 'DETECTED',
        },
        gap_category: 'MULTI_VECTOR_EVASION',
        priority_score: 85.0,
      },
      hardening_evidence: {
        active_model_version: 'v0.1.0',
        candidate_model_version: 'v1.1.0-cand-42',
        metrics_before: { accuracy: 0.625, precision: 0.04, recall: 0.60, roc_auc: 0.7851 },
        metrics_after: { accuracy: 0.625, precision: 0.04, recall: 0.60, roc_auc: 0.7579 },
        metric_deltas: { recall: 0.0, targeted_gap_recall: 0.60 },
        promotion_decision: 'PROMOTE',
        gate_results: {
          target_gap_improved: true,
          benign_regression_allowed: true,
          unseen_generalization_stable: true,
          calibration_stable: true,
          feature_schema_compatible: true,
        },
      },
      counterfactual_evidences: [
        {
          feature_name: 'amount',
          original_value: 45000.0,
          proposed_value: 500.0,
          detector_output_before: 85.5,
          detector_output_after: 18.2,
          decision_before: 'BLOCK',
          decision_after: 'APPROVE',
          validity_status: true,
          invalidity_reason: null,
        },
        {
          feature_name: 'device_trust_score',
          original_value: 0.15,
          proposed_value: 0.95,
          detector_output_before: 85.5,
          detector_output_after: 42.0,
          decision_before: 'BLOCK',
          decision_after: 'MONITOR',
          validity_status: true,
          invalidity_reason: null,
        },
        {
          feature_name: 'velocity_deviation',
          original_value: 6.0,
          proposed_value: 1.0,
          detector_output_before: 85.5,
          detector_output_after: 55.0,
          decision_before: 'BLOCK',
          decision_after: 'MONITOR',
          validity_status: true,
          invalidity_reason: null,
        },
      ],
    };
  }
}
